Console.Clear();
int numA = 2;
int numB = 8;
int numC = 4;
int numD = 15;
int numE = 0;
int max = numA;
if (numB > max) max = numB;
if (numC > max) max = numC;
if (numD > max) max = numD;
if (numE > max) max = numE;
Console.Write("Максимальное число равно ");
Console.WriteLine(max);